### ISSUE TITLE
Wegen des erzwungenen HTTPS' kann man nicht über die DNS-Namen der Knoten deren Statusseiten abrufen

### ISSUE THREAD

**Issue by MPW1412** [FreiFunkMuenster/ansible-ffms#27]
Moin,

dank @Fungur69 haben wir für alle Knoten einen DNS-Namen: knotenname.knoten.freifunk-muensterland.de.

Leider kann man nicht im Browser auf knotenname.knoten.freifunk-muensterland.de oder http://knotenname.knoten.freifunk-muensterland.de/ gehen, weil irgendwo hinterlegt ist, dass für unsere Domäne immer https genutzt werden kann und soll.

Kann man das abschalten?

Grüße
Matthias

**Comment by MPW1412** [comment]
Laut @descilla ist der Eintrag im Webserver draran schuld:

`add_header Strict-Transport-Security "max-age=31536000; includeSubdomains;";`

**Comment by kgbvax** [comment]
Einfach das "includeSubdomains" entfernen, fertig.

**Comment by MPW1412** [comment]
Ich habe die Subdomains entfernt. Jetzt ist mir auch klar, an welcher Stelle das gesetzt wurde :).
