### ISSUE TITLE
Branches aufräumen

### ISSUE THREAD

**Issue by descilla** [FreiFunkMuenster/ansible-ffms#28]
Ich habe gerade gesehen, dass sich hier mittlerweile eine Vielzahl von Branches angesammelt hat.
-  graphiteumzug
- master
- bb-fanlin
- collectd_v4v6_traffic
- dom-ms
- entwicklungszweig
- graphiteumzug
- kgbvax-patch-2
- master
- owner2
- radvd_config
- remove-old-crypto
- ssh-schluesselverwaltung
- tests
- testserver-greanbindung-wml

Welche davon brauchen wir nicht mehr?

**Comment by MPW1412** [comment]
Ich glaube, dass die alle weg können, bis auf master natürlich.

Mir ist nicht bekannt, dass jemand derzeit Featurezweige pflegt. 

Zur Sicherheit nochmal @elberfeld fragen, da ich nicht genau weiß, woran er gerade so schraubt.

**Comment by MPW1412** [comment]
Die Zweige kgbvax-patch-X können auch weg, weil sie in den Hauptzweig überführt wurden.

**Comment by MPW1412** [comment]
Alle gelöscht bis auf den Zweig um den Tunneldigger auf die Upstreamversion umzustellen, da wir das ggfs. nochmal brauchen können, wenn die den CPU-Load-Bug gefixt haben.
