### ISSUE TITLE
Tunnel zu nicht im der hosts stehenden VMs führt zu Abbruch

### ISSUE THREAD

**Issue by MPW1412** [FreiFunkMuenster/ansible-ffms#29]
TASK [interfaces_ffms_backbone : Create interfaces - tunnels to ffms supernodes] ***
fatal: [fanlin]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: ERROR! 'type object' has no attribute 'ansible_ssh_host'"}

PLAY RECAP *********************************************************************
fanlin                     : ok=30   changed=4    unreachable=0    failed=1

**Comment by Fungur69** [comment]
Ich denke, alle MS-VMs, die irgendwo in Ansible auftauchen, sollten auch in der hosts-Datei stehen. Ansonsten fehlt grundlegende Information. Wahrscheinlich ist dies auch nicht die einzige Stelle, an der wir davon ausgehen.

**Comment by MPW1412** [comment]
Alles klar, wird nicht geändert, geschlossen.
