### ISSUE TITLE
Nach Kernelupdate reboot

### ISSUE THREAD

**Issue by MPW1412** [FreiFunkMuenster/ansible-ffms#30]
Moin,

beim heute komplett frisch aufgezogenen Server Des2 (Multidomänen-und-Batman-Gateway-Konfiguration) lief der Tunneldigger nicht, weil der Kernel zu alt war. Der neue wurde korrekt installiert, aber das System am Ende nicht rebootet.

Wir brauchen sowas wie: Neuer Kernel -> reboot

Grüße
Matthias

**Comment by Fungur69** [comment]
Hier ist ein Skript, das ich eben zusammengebaut habe und ausgibt, ob ein Reboot nötig ist (man könnte natürlich auch direkt rebooten):

```
#!/bin/bash
v1=$(uname -v)
v2=${v1#*Debian }
running=${v2% (*}
for installed in $(dpkg-query -W -f '${Version}\n' linux-image*); do
  if dpkg --compare-versions $installed gt $running; then
    echo "Reboot needed: Kernel installed: $installed, running: $running"
  fi
done
```

Man könnte sowas mit automatischem Reboot in nen Handler in `roles/backports-kernel/tasks/main.yml` einbauen, mit dem wir ja den Kernel installieren. Aber ich weiß nicht, ob das dann nicht immer noch zu früh auslöst.

**Comment by MPW1412** [comment]
Man kann doch irgendwie abfragen, ob jemand eingeloggt ist? Ansible baut auch eine SSH-Verbindung aus. Man könnte einen Befehl absetzen, der rebootet, wenn die Bedingungen des Skriptes von dir erfüllt sind und dann diesen verzögert, bis niemand mehr eingeloggt ist, respektive Ansible fertig ist.

**Comment by FanLin-ffms** [comment]
Mit "w" kann man sehen wer noch auf dem Blech ist.

**Comment by SISheogorath** [comment]
Effektiver wäre es, den Reboot in Ansible abzufangen:

https://www.linux.com/blog/ansible-reboot-server-play-book-and-wait-it-come-back

Kein Grund sich Shellscripte aus den Fingern zu saugen ;)

**Comment by MPW1412** [comment]
Klingt gut. Aber wir sollten das als handler und nicht als allgemeinen shell-Befehl umsetzen. Benötigt für die set_kernel_param_maxcpus und die Kernelinstallation.

Wenn etwas geändert wurde, bitte neu starten und darauf warten.

Gibt es eine Möglichkeit durch einen handler alle anderen zu unterdrücken? Wenn wir neu booten, brauchen wir z. B. keinen Netzwerkneustart mehr.

**Comment by MPW1412** [comment]
Reboot funktioniert schon mal, aber Ansible bricht ab: Vermutlich passt was mit dem Timing noch nicht. Teilweise hab ich im Netz gesehen, dass davor noch sleep-Befehle stehen: 

https://github.com/FreiFunkMuenster/Ansible-Freifunk-Gateway/commit/d9519e45fc2cdaba80c316779d2179b8ae6a8896
