### ISSUE TITLE
Interfaces werden nach networking restart nicht wieder in die bat-Interfaces gehangen

### ISSUE THREAD

**Issue by MPW1412** [FreiFunkMuenster/ansible-ffms#31]
Moin,

nach einem networking restart sind die bat-Interfaces in der Multidomänen-L2TP-Konfiguration leer. Somit sind die Knoten offline und sie merken es auch nicht, weil die L2TP-Tunnel an sich stehen.

Eventuell müssten die Interfaces in der interfaces explizit nochmal in die Brücken gehängt werden.

Grüße
Matthias

**Comment by Fungur69** [comment]
Nach einem Network-Restart muss der Tunneldigger restartet werden. In den 4 Gateway-Rollen, die einen Network-Restart durchführen, habe ich es im Restart-Handler schon eingebaut gehabt.

Die Frage ist jetzt, hat der Handler nicht funktioniert, ist eine andere Rolle nicht angepasst oder wurde manuell restartet?

**Comment by MPW1412** [comment]
Es wurde manuell neu gestartet. Sollte gelöst sein.
