### ISSUE TITLE
Netzwerk Neustart lässt Dienste abschmieren

### ISSUE THREAD

**Issue by MPW1412** [FreiFunkMuenster/ansible-ffms#32]
Moin,

ich glaube, dass ein Netzwerkneustart den DHCP-Server abschießt. Der kommt scheinbar nicht damit klar, wenn das Interface kurz weg ist.

Neben dem Tunneldigger müssen also auch der DHCP-Server und bird6 neu gestartet werden. Bei letzterem ist mir nicht klar, ob ein configure reicht oder ein Neustart erforderlich ist.

Grüße
Matthias

**Comment by Fungur69** [comment]
Die Nerwork-Restart-Handler in Ansible restarten auch schon den DHCP-Server. Das mit bird6 ist neu und muss dann ggf. noch mit eingebaut werden.

Was wir aber wohl auch brauchen, ist eine Liste mit Hinweise zur manuellen Administration. Z.B. was alles beim Netzwerk-Neustart zu beachten ist oder wie man Netzwerk- und Bird-Status überprüft. Also doch etwas Doku außerhalb von Ansible.

**Comment by MPW1412** [comment]
Sollte durch die Commits vom Sonntag gelöst sein.

**Comment by MPW1412** [comment]
Argh leider doch noch nicht:
- [x] interfaces_batman: Hier fehlt Bird6 und der DHCP-Server im Handler
- [x] interfaces_bridge: bird6 fehlt bzw. wird die Rolle noch benötigt, ist in keiner yml-Datei mehr drin

Warum arbeiten wir eigentlich mit dem Shell-Befehl und nicht mehreren restarted-Anweisungen wie in der interfaces_batman?
