### ISSUE TITLE
Roles auslagern

### ISSUE THREAD

**Issue by SISheogorath** [FreiFunkMuenster/ansible-ffms#33]
Da die [Anleitung im Forum](https://forum.freifunk.net/t/anleitung-gateway-aufsetzen-fuer-neulinge/11793) vermutlich gerne von kleineren Communities genutzt werden wird, wäre es sicher sinnvoll die roles in ein Submodule oder einen Subtree auszulagern. Hierdurch könnte man die Rollen optimaler maintainen da ein Fork der config nicht auch alle Rollen unlinkt und so das Updaten für alle einfacher wird. 

Man kann natürlich auch kreuz und quer mergen, aber da geht sicher einiges kaputt.

**Comment by MPW1412** [comment]
Find ich super :)

Ich hatte dir dazu im Forum auch geantwortet.

**Comment by MPW1412** [comment]
@8d719f8, @33ec4b8

Erledigt ✓
