### ISSUE TITLE
Backbone in group_vars required

### ISSUE THREAD

**Issue by SISheogorath** [FreiFunkMuenster/ansible-ffms#34]
Against the [Tutorial in the FF Forum](https://forum.freifunk.net/t/anleitung-gateway-aufsetzen-fuer-neulinge/11793?u=sheogorath) the values from backbone-group is required to setup a gateway successful.

And the value `ffms_routing` isn't really generic.

**Comment by MPW1412** [comment]
There's just an empty group required. No host in it.

This project wasn't started to be generic, but it we're modifying it to be. Feel free to find a better name, replace it and send a PR.

**Comment by MPW1412** [comment]
@Fungur69: Kann man auf die Existenz von Gruppen testen? Wir haben eh nur noch Greyworm-07 als reines Backbone. Und dessen Tage sind gezählt, auch wenn es noch ein paar Monate dauern dürfte, bis wir die Kiste abschalten können.

Ich glaube daher, dass es sich nicht lohnt, hier Zeit reinzustecken und dass wir das rausnehmen, wenn Greyworm abgeschaltet wird.

**Comment by MPW1412** [comment]
Fixed by Ansible-Freifunk-Gateway/#48aceb712d2
