### ISSUE TITLE
services Host is required to setup Gateway

### ISSUE THREAD

**Issue by SISheogorath** [FreiFunkMuenster/ansible-ffms#35]
the services host should not be required to deploy a gateway. For stand alone tests it breaks.

(may add an default value?)

For example by deploying GRE-TAB and bind

**Comment by MPW1412** [comment]
You can insert any ip you want to. 

But it could be optionalized, so that ansible doesn't fail if there's not service-vm set. Not a high priority to me as everybody will want to have a map, but a PR will be accepted.

**Comment by MPW1412** [comment]
Ich hab mir das gerade mal näher angesehen. Also die einzigen Rollen, die auf die Service-VM referenzieren, sind bind_backbone, bind_gateway, gateways_bind und gateways_gretap.

Mir ist nicht ganz klar, warum es bind_gateway und gateways_bind gibt. Vermutlich ist das erste überholt.

Die Backbone-Konstruktion wird auch nicht mehr gepflegt, daher müsste man nur die
- [x] gateways_bind
- [x] gateways_gretap
- [x] gateways_l2tp

anpassen.

**Comment by MPW1412** [comment]
Sollte gelöst sein.
