### ISSUE TITLE
local7 log facility für DHCP request logging

### ISSUE THREAD

**Issue by kgbvax** [FreiFunkMuenster/ansible-ffms#50]
DHCP requests landen zur Zeit im /var/log/messages und unterliegen damit der normalen log-rotation.
Auf Barristan sind das z.b. ein Monat. d.h. ein Montag lang bewahren wir auf welches Device welche NAT IP hatte. Suboptimal. Auch wenn das für debugging gut ist sollte es nicht so lange aufbewahrt werden. 

das dhcpd logging ist schon auf logging faciulity "local7" eingestellt, nur scheint die in der syslog conf nicht zu existieren. 
In /etc/rsyslog.conf fehlt also  IMHO die local7.\* facility sowie der Ausschluss das in die Default Facilities zu loggen. Im Wiki steht wies geht :-)

**Comment by MPW1412** [comment]
Wir haben jetzt die Logrotation auf drei Tage einstellt. Ist das hier dadurch noch relevant?

**Comment by MPW1412** [comment]
In Rücksprache mit @kgbvax obsolet und somit geschlossen.
