### ISSUE TITLE
logrotate.conf - vier Wochen Logs aufbewahren

### ISSUE THREAD

**Issue by kgbvax** [FreiFunkMuenster/ansible-ffms#51]
Im /etc/logrotate.conf steht alles noch auf Default, d.h. wöchentliche Rotation und 4 Wochen. 
Solange wir die "empfindlichen Logs" nicht runterdrehen (siehe DHCP) sollten wir hier die Zeit zumindest auf das reduzieren was wir operativ brauchen. 2 Tage?

Die ersten Zeilen sollte IMHO  so lauten. Gibt es noch nicht im Ansible, sonst hätte ich dafür ein PR gemacht,

```
# see "man logrotate" for details
# rotate log files daily
daily

# keep 3 days worth of backlogs
rotate 3

```

**Comment by MPW1412** [comment]
Ich würde sagen, das schmeißen wir in die common rein, oder brauchen wir dafür eine eigene Rolle?
