### ISSUE TITLE
Keine automatischen Tunnel (*-karte)

### ISSUE THREAD

**Issue by stefan6ffnw** [FreiFunkMuenster/ansible-ffms#63]
Hallo zusammen,

wir würden uns wünschen, wenn die Tunnel für die Karte nicht automatisch mit erstellt werden, erst, wenn diese in der Config gesetzt wurden:

14: t120-karte@ens18: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1458 qdisc pfifo_fast master bat120 state UNKNOWN group default qlen 1000
    link/ether de:ad:be:ef:01:02 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::dcad:beff:feef:102/64 scope link
       valid_lft forever preferred_lft forever
15: t160-karte@ens18: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1458 qdisc pfifo_fast master bat160 state UNKNOWN group default qlen 1000
    link/ether de:ad:be:ef:02:02 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::dcad:beff:feef:202/64 scope link
       valid_lft forever preferred_lft forever

VG
Stefa

**Comment by HellMar** [comment]
Moinsen, 

Ich sehe grade die Tunnel werden nur dann erzeugt wenn auch eine Karten VM in der hosts definiert wurde. 
Ggf. solltest du einfach mal den dummy "karte" aus eurer hosts entfernen ;-)
