### ISSUE TITLE
Yanic via Ansible

### ISSUE THREAD

**Issue by stefan6ffnw** [FreiFunkMuenster/ansible-ffms#64]
Hallo zusammen,

damit wir unser komplettes Setup auf euer Ansbile umstellen können, wäre Yanic für die Gateways wünschenswert. @HellMar sagt mir, dass es hier schon Vorarbeit gab.

VG
Stefan

**Comment by MPW1412** [comment]
Das hier ist leider das falsche Repo dafür. Hier liegt nur unsere eigene Konfiguration. Das allgemeine Rollen-Repo gibt es hier:

https://github.com/FreiFunkMuenster/Ansible-Freifunk-Gateway/
